---
jpm: https://github.com/JuanjoSalvador/JuanjoPackageManager.git"
jekyll: https://github.com/JuanjoSalvador/JuanjoPackageManager.git"
moc-twitter-sharing: "https://github.com/JuanjoSalvador/JuanjoPackageManager.git"
azufaifo: "https://github.com/JuanjoSalvador/JuanjoPackageManager.git"