---
jpm: 
    desc: "Juanjo's Package Manager"
    repo: "https://github.com/JuanjoSalvador/JuanjoPackageManager.git"
jekyll: 
    desc: "Static Blog Aware Page Generator"
    repo: "https://github.com/JuanjoSalvador/JuanjoPackageManager.git"
moc-twitter-sharing: 
    desc: ""
    repo: "https://github.com/JuanjoSalvador/JuanjoPackageManager.git"
azufaifo: 
    desc: ""
    repo: "https://github.com/JuanjoSalvador/JuanjoPackageManager.git"